apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pixel
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: {{ .Values.spec.source.path }}
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    plugin:
      name: helmfile
      env:
        - name: HELMFILE_ARGS
          value: "--set resources.requests.cpu=0 --set resources.requests.memory=0 --set resources.limits.cpu=0 --set resources.limits.memory=0 --set repoUrl=gcr.io/rtr-e2e-4f85741f --set istio.sideCarEnabled=false --set serviceType=LoadBalancer"

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
