server:
  extraArgs:
    - --insecure
  service:
    type: LoadBalancer
    servicePortHttp: 8080

  # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  config:
    configManagementPlugins: |
      - name: helmfile
        init:
          command: ["/bin/sh", "-c"]
          args:
            # NOTE: This secret must be imported into the cluster ahead of time
            - kubectl get secret -n default sops-private-key -o jsonpath='{.data.key}' | base64 --decode | gpg --import
        generate:
          command: ["/bin/sh", "-c"]
          # https://argoproj.github.io/argo-cd/user-guide/build-environment/
          # TODO: Additional args
          args:
            - |
              echo "namespace: rtr" > ../.values.yaml
              helmfile --selector app=${ARGOCD_APP_NAME} -f rtr.yaml -e e2e template --skip-deps "${HELMFILE_ARGS}"
repoServer:
  initContainers:
    - name: download-tools
      image: alpine:3.8
      command: [sh, -c]
      args:
        - |
          wget -qO /custom-tools/helmfile https://github.com/roboll/helmfile/releases/download/v0.98.2/helmfile_linux_amd64 &&
          chmod +x /custom-tools/helmfile
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumes:
    - name: custom-tools
      emptyDir: {}
  volumeMounts:
    - mountPath: /usr/local/bin/helmfile
      name: custom-tools
      subPath: helmfile

# https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd#helm-v3-compatability
installCRDs: false
